//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASyncClient.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NumberToWords", ReplyAction="http://tempuri.org/IService1/NumberToWordsResponse")]
        string NumberToWords(int number);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/NumberToWords", ReplyAction="http://tempuri.org/IService1/NumberToWordsResponse")]
        System.IAsyncResult BeginNumberToWords(int number, System.AsyncCallback callback, object asyncState);
        
        string EndNumberToWords(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ASyncClient.ServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NumberToWordsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public NumberToWordsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ASyncClient.ServiceReference.IService1>, ASyncClient.ServiceReference.IService1 {
        
        private BeginOperationDelegate onBeginNumberToWordsDelegate;
        
        private EndOperationDelegate onEndNumberToWordsDelegate;
        
        private System.Threading.SendOrPostCallback onNumberToWordsCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<NumberToWordsCompletedEventArgs> NumberToWordsCompleted;
        
        public string NumberToWords(int number) {
            return base.Channel.NumberToWords(number);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginNumberToWords(int number, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginNumberToWords(number, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndNumberToWords(System.IAsyncResult result) {
            return base.Channel.EndNumberToWords(result);
        }
        
        private System.IAsyncResult OnBeginNumberToWords(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int number = ((int)(inValues[0]));
            return this.BeginNumberToWords(number, callback, asyncState);
        }
        
        private object[] OnEndNumberToWords(System.IAsyncResult result) {
            string retVal = this.EndNumberToWords(result);
            return new object[] {
                    retVal};
        }
        
        private void OnNumberToWordsCompleted(object state) {
            if ((this.NumberToWordsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.NumberToWordsCompleted(this, new NumberToWordsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void NumberToWordsAsync(int number) {
            this.NumberToWordsAsync(number, null);
        }
        
        public void NumberToWordsAsync(int number, object userState) {
            if ((this.onBeginNumberToWordsDelegate == null)) {
                this.onBeginNumberToWordsDelegate = new BeginOperationDelegate(this.OnBeginNumberToWords);
            }
            if ((this.onEndNumberToWordsDelegate == null)) {
                this.onEndNumberToWordsDelegate = new EndOperationDelegate(this.OnEndNumberToWords);
            }
            if ((this.onNumberToWordsCompletedDelegate == null)) {
                this.onNumberToWordsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnNumberToWordsCompleted);
            }
            base.InvokeAsync(this.onBeginNumberToWordsDelegate, new object[] {
                        number}, this.onEndNumberToWordsDelegate, this.onNumberToWordsCompletedDelegate, userState);
        }
    }
}
